name: Build and Deploy
on:
  push:
    branches:
      - main
      
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          deploy-branch: gh-pages
